# yaml-language-server: $schema=./values.schema.json

global:
  domain: c-5685dc1.kyma.ondemand.com
  imagePullSecret:
    name: docker-registry
  image:
    registry: <your-container-registry-server>
    tag: latest
srv:
  bindings:
    auth:
      serviceInstanceName: xsuaa
    service-manager:
      serviceInstanceName: service-manager
    destination:
      serviceInstanceName: destination
  image:
    repository: RiskManagement2-srv
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /health
    readiness:
      path: /health
  networkSecurity:
    allowNamespaceInternal: true
sidecar:
  bindings:
    auth:
      serviceInstanceName: xsuaa
    saas-registry:
      serviceInstanceName: saas-registry
    service-manager:
      serviceInstanceName: service-manager
    html5-apps-repo-host:
      serviceInstanceName: html5-apps-repo-host
  image:
    repository: RiskManagement2-sidecar
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /health
    readiness:
      path: /health
  env:
    SUBSCRIPTION_URL: https://${tenant_subdomain}-{{ .Release.Name }}-approuter-{{ .Release.Namespace }}.{{ .Values.global.domain }}
  networkSecurity:
    allowNamespaceInternal: true
approuter:
  bindings:
    auth:
      serviceInstanceName: xsuaa
    html5-apps-repo-runtime:
      serviceInstanceName: html5-apps-repo-runtime
  image:
    repository: RiskManagement2-approuter
  env:
    TENANT_HOST_PATTERN: ^(.*)-{{ .Release.Name }}-approuter-{{ .Release.Namespace }}.{{ .Values.global.domain }} # change if expose.host is set
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /
    readiness:
      path: /
  envFrom:
    - configMapRef:
        name: "{{ .Release.Name }}-approuter-configmap"
xsuaa:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    tenant-mode: shared
    oauth2-configuration:
      redirect-uris:
        - https://*.{{ tpl .Values.global.domain . }}/**
    xsappname: RiskManagement2-{{ .Release.Namespace }}
service-manager:
  serviceOfferingName: service-manager
  servicePlanName: container
saas-registry:
  serviceOfferingName: saas-registry
  servicePlanName: application
  parameters:
    appName: RiskManagement2-{{ .Release.Namespace }}
    xsappname: RiskManagement2-{{ .Release.Namespace }}
    displayName: RiskManagement2
    description: A simple CAP project.
    category: "CAP Application"
    appUrls:
      onSubscriptionAsync: true
      onUnSubscriptionAsync: true
      onUpdateDependenciesAsync: true
      callbackTimeoutMillis: 300000
      getDependencies: https://{{ .Release.Name }}-sidecar-{{ .Release.Namespace }}.{{ .Values.global.domain }}/-/cds/saas-provisioning/dependencies
      onSubscription: https://{{ .Release.Name }}-sidecar-{{ .Release.Namespace }}.{{ .Values.global.domain }}/-/cds/saas-provisioning/tenant/{tenantId}

mtx-upgrade:
  bindings:
    service-manager:
      serviceInstanceName: service-manager
  image:
    repository: RiskManagement2-sidecar
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 1G
    requests:
      ephemeral-storage: 1G
      cpu: 1000m
      memory: 1G
  command:
    - "launcher"
  args:
    - "cds-mtx"
    - "upgrade"
    - '*'
backendDestinations:
  srv-api:
    service: srv
    Authentication: OAuth2UserTokenExchange
  mtx-api:
    service: sidecar
destination:
  serviceOfferingName: destination
  servicePlanName: lite
  parameters:
    version: 1.0.0
    HTML5Runtime_enabled: true
html5-apps-repo-host:
  serviceOfferingName: html5-apps-repo
  servicePlanName: app-host
html5-apps-deployer:
  env:
    SAP_CLOUD_SERVICE: RiskManagement2.service
  image:
    repository: RiskManagement2-html5-deployer
  bindings:
    xsuaa:
      serviceInstanceName: xsuaa
    destination:
      serviceInstanceName: destination
    html5-apps-repo:
      serviceInstanceName: html5-apps-repo-host
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
  envFrom:
    - configMapRef:
        name: "{{ .Release.Name }}-html5-apps-deployer-configmap"
html5-apps-repo-runtime:
  serviceOfferingName: html5-apps-repo
  servicePlanName: app-runtime
